name: Build and Push to GHCR-test 1

on:
  push:
    branches: [ main ]   # 每次推送到 main 分支时触发

permissions:
    packages: write
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write    # 允许推送至 GHCR

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 登录 GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 构建并标记镜像
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/node-action-app:latest
          docker build -t $IMAGE_NAME .
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: 推送镜像
        run: docker push ${{ env.IMAGE_NAME }}
