name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
       matrix:
        node-version: [18.x, 20.x, 22.x]   # 👈 同时测试这三个版本
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
           node-version: ${{ matrix.node-version }}
           cache: 'npm'                     # 👈 自动缓存 npm 依赖
      - run: npm install
      - run: npm test
